# Generated by Django 3.2.8 on 2022-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('ilc', models.CharField(max_length=100, null=True, verbose_name='Ilc')),
                ('nacion', models.CharField(max_length=100, null=True, verbose_name='Nacion')),
                ('idioma', models.CharField(max_length=100, null=True, verbose_name='Idioma')),
            ],
        ),
    ]
