# Generated by Django 3.2.8 on 2022-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre_departamento',
            new_name='nombre_dep',
        ),
        migrations.AlterField(
            model_name='ilc',
            name='nacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Nación'),
        ),
    ]
