# Generated by Django 3.2.8 on 2022-06-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20220629_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Departamentos',
        ),
        migrations.RenameModel(
            old_name='Ilc',
            new_name='Ilcs',
        ),
    ]
