# Generated by Django 3.2.8 on 2022-06-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20220629_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamentos',
        ),
        migrations.DeleteModel(
            name='Ilcs',
        ),
    ]
