# Generated by Django 3.2.8 on 2022-06-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libreria', '0005_auto_20220629_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=100, null=True, verbose_name='Departamento')),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ilcs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('ilc', models.CharField(max_length=100, null=True, verbose_name='Ilc')),
                ('nacion', models.CharField(max_length=100, null=True, verbose_name='Nación')),
                ('idioma', models.CharField(max_length=100, null=True, verbose_name='Idioma')),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
