# Generated by Django 3.2.8 on 2022-06-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_auto_20220629_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='estado_dep',
            new_name='estado_departamento',
        ),
        migrations.RenameField(
            model_name='departamentos',
            old_name='nombre_dep',
            new_name='nombre_departamento',
        ),
    ]
