# Generated by Django 3.2.8 on 2022-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_auto_20220629_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='estado_departamento',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ilcs',
            name='estado_ilc',
            field=models.BooleanField(),
        ),
    ]
