# Generated by Django 3.2.8 on 2022-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_auto_20220629_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='estado_departamento',
            new_name='estado_depa',
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='nombre_departamento',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='nombre_depa',
            field=models.CharField(max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='ilcs',
            name='idioma',
            field=models.CharField(max_length=50, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='ilcs',
            name='ilc',
            field=models.CharField(max_length=50, null=True, verbose_name='Ilc'),
        ),
        migrations.AlterField(
            model_name='ilcs',
            name='nacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Nación'),
        ),
    ]
