# Generated by Django 3.2.8 on 2022-06-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_auto_20220630_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilcs',
            options={'ordering': ['idioma'], 'verbose_name': 'Ilc', 'verbose_name_plural': 'Ilcs'},
        ),
        migrations.AlterField(
            model_name='ilcs',
            name='estado_ilc',
            field=models.BooleanField(default='1', verbose_name='Activo'),
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table='departamentos',
        ),
        migrations.AlterModelTable(
            name='ilcs',
            table='ilcs',
        ),
    ]
