# Generated by Django 3.2.8 on 2022-07-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_auto_20220630_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=30, null=True, verbose_name='Nombre Provincia')),
                ('estado_provincia', models.BooleanField(default='1')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
    ]
