# Generated by Django 3.2.8 on 2022-07-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_provincias_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilcs',
            name='region',
            field=models.CharField(max_length=50, null=True, verbose_name='Region'),
        ),
    ]
