# Generated by Django 3.2.8 on 2022-07-03 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_coordinaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivosEstrategicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objetivo', models.CharField(max_length=30, null=True, verbose_name='Objetivo Estratégico')),
                ('estado_objetivo', models.BooleanField(default='1')),
                ('coordinacion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.coordinaciones')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'db_table': 'objetivos',
                'ordering': ['nombre_objetivo'],
            },
        ),
    ]
