# Generated by Django 3.2.8 on 2022-07-03 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_objetivosestrategicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivosestrategicos',
            name='coordinacion_id',
        ),
        migrations.AddField(
            model_name='objetivosestrategicos',
            name='coordinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.coordinaciones', verbose_name='Coordinacion '),
        ),
        migrations.AlterField(
            model_name='coordinaciones',
            name='nombre_coordinacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Coordinación'),
        ),
        migrations.AlterField(
            model_name='objetivosestrategicos',
            name='nombre_objetivo',
            field=models.CharField(max_length=100, null=True, verbose_name='Objetivo Estratégico'),
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('lugar_actividad', models.CharField(max_length=50, verbose_name='Lugar de la Actividad')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de realización')),
                ('cantidad_dias', models.FloatField(max_length=5, verbose_name='Porcentaje Programado')),
                ('coordinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.coordinaciones', verbose_name='Cordinación con unidad del IPELC ')),
                ('objetivo_estrategico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.objetivosestrategicos', verbose_name='Objetivo Estrategico ')),
            ],
        ),
    ]
