# Generated by Django 3.2.8 on 2022-07-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20220702_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='fechaInicio',
        ),
        migrations.AddField(
            model_name='actividades',
            name='observacion',
            field=models.TextField(max_length=200, null=True, verbose_name='Cantidad de Dias'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='cantidad_dias',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Dias'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='coordinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.coordinaciones', verbose_name='Cordinación con unidad del IPELC'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='objetivo_estrategico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.objetivosestrategicos', verbose_name='Objetivo Estrategico'),
        ),
        migrations.AlterModelTable(
            name='actividades',
            table='actividades',
        ),
    ]
