# Generated by Django 3.2.8 on 2022-07-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_auto_20220703_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='observacion',
            field=models.TextField(max_length=200, null=True, verbose_name='Observacion'),
        ),
    ]
