# Generated by Django 3.2.8 on 2022-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_alter_actividades_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='archivo',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Adjuntar en pdf Planificacion'),
        ),
    ]
