# Generated by Django 3.2.8 on 2022-07-03 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_actividades_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='fechainicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
