# Generated by Django 3.2.8 on 2022-07-06 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_actividades_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fechainicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de la Actividad'),
        ),
    ]
