# Generated by Django 3.2.8 on 2022-07-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0024_funcionarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'ordering': ['primerapellido'], 'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterModelTable(
            name='funcionarios',
            table='funcionarios',
        ),
    ]
