# Generated by Django 3.2.8 on 2022-07-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0025_auto_20220706_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='nomsegundoapellido',
            new_name='segundoapellido',
        ),
    ]
