# Generated by Django 3.2.8 on 2022-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0026_rename_nomsegundoapellido_funcionarios_segundoapellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinaciones',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=10, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='coordinaciones',
            name='nombre_coordinacion',
            field=models.CharField(max_length=50, verbose_name='Nombre Coordinación'),
        ),
    ]
